### ISSUE TITLE
Get `make bootstrap` working again

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#111]
`make bootstrap` has not worked in a while.  Please figure out how to fix it.

Currently, the development environment can only build on existing snapshots.  For jhu-idc/idc-general#295, we will need to create a clean "initial snapshot".  The current snapshot for `idc-isle-dc` is "dirty", as it contains some "convenience" data in it, and past mistakes.  In order to create a clean snapshot, we need to start from a clean islandora install.  `make bootstrap` was the easiest and most straightforward way to do that

**Comment by htpvu** [comment]
@birkland who should this be assigned to?
