### ISSUE TITLE
Error about FITS file on Media creation

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#112]
When one creates a Media on a Repository Item, the following error shows up: 

![Screen Shot 2021-04-13 at 4 46 46 PM](https://user-images.githubusercontent.com/7966375/114618936-f5929e00-9c77-11eb-983d-ee1f4e2b13b4.png)

Something about the FITS derivative creation isn't functioning correctly and probably needs to be looked into.

**Comment by htpvu** [comment]
TODO: @htpvu check with katie about whether technical metadata extracted from the media is required.

**Comment by bseeger** [comment]
If the answer is that we don't need FITS we can take a few services/containers out and simplify the iDC stack.

**Comment by bseeger** [comment]
I've realized that the error here is that URL in the Islandora Media Use FITS File term was was deleted from the Taxonomy term. Adding it back in fixes the issue.   (Putting `https://projects.iq.harvard.edu/fits` in the `External URL` URL field.

**Comment by bseeger** [comment]
The one thing I'm unsure about is how it gets there in the first place.... I've been unable to track that through the code. It's definitely content, so there must be a migration somewhere?
