### ISSUE TITLE
CLAs: should they be able to change access_terms? 

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#115]
Access controls are managed through a field named `field_access_terms` on a Collection and Repository Item.  Right now a CLA can edit the `field_access_terms` on an object, thereby changing them. They are limited in scope though and only able to use terms that they have access to.  But they can leave it blank thereby removing their own access to it. 

We need to figure out how locked down this field should be.  Should the CLA be able to change this value?  When adding a new object, should the field default to the parent object's permission?   What if there is no parent object for it? 

It is possible to default this value - it is done now via the islandora module for the `member_of` field if someone adds a child object to something. We could expand this to include the `field_access_terms` field.

**Comment by htpvu** [comment]
blocker for acceptance testing.

**Comment by bseeger** [comment]
Ask stakeholders about this. Describe path to recovery should a CLA lock themselves (their group) out of a record.

**Comment by bseeger** [comment]
If a CLA is able to change the field_access_terms, they can, effectively lock themselves out of the content grouping, and thereby lose access. 

They can only assign access terms of the groups that they are a part of, so there's no concern about escalating permissions here, but should they remove the value from the field altogether (unsetting it), they will lose access to the record upon saving.  They will then have to seek help from a Global Admin to get edit access to that record back.

**Comment by bseeger** [comment]
If a CLA cannot access that field, we will need to do a little more customization to make sure that field is set in the first place, so that it inherits either it's parent object's access_terms or some sort of default for the user.   This will be a little more work - maybe a day to pull it together.

**Comment by bseeger** [comment]
I think it was discussed to allow them to have access to the field in a meeting, but my memory is a little fuzzy here.  It will be harder, tech-wise, for us if we don't let them access that field, as mentioned in the last comment.   We could make it so they _have_ to set a value - so they can never leave it blank.    Personally, I think that option makes the most sense.  Let them edit it and it must have a value.

**Comment by bseeger** [comment]
Decision:  make Access Terms a required field, where a value must be set.  Then the CLA's can choose the value AND they can't leave it blank.   (noting that the only values available to them are the groups they are apart of).
