### ISSUE TITLE
Test Cloud instance doesn't accept files for upload

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#116]
On our [test instance](http://test.digital.library.jhu.edu/) I can't seem to upload files as part of creating Media. 

To reproduce: 
 - Log in
 - Click on Manage->Content->Media -> Add Media
 - Pick Image Media Type
 - Click on Browse, in the file box.  Choose a JPG image and click Open. 
 
I get these results: 

![Screen Shot 2021-04-23 at 12 41 44 PM](https://user-images.githubusercontent.com/7966375/115903211-50bf5000-a431-11eb-8b21-321cec4ebf5b.png)

**Comment by bseeger** [comment]
Just noticed this error on the Drupal reports page: 
```
User warning: mkdir(): Permission Denied in Drupal\Component\PhpStorage\FileStorage->createDirectory() (line 145 of /var/www/drupal/web/core/lib/Drupal/Component/PhpStorage/FileStorage.php) 
```
and 
```
The upload directory public://2021-04 for the file field field_media_image could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.
```

**Comment by jhujasonw** [comment]
What would be the filesystem directory that "public://2021-04" should translate to in the container?  Once I know the answer to that question, I an investigate why the container would have an issue writing to that directory.

Also, it is possible that https://github.com/jhu-idc/idc-isle-dc/pull/121 may help with some of these issues, but discussion on that is probably needed.

**Comment by jhujasonw** [comment]
Blocked by https://github.com/jhu-idc/idcApp-k8s/issues/43

Test instance issue with cantaloupe is resolved, unblocking this issue which I believe @bseeger said was resolved.  Closing issue.
