### ISSUE TITLE
Re-tag all Docker images using idc-isle-dc commit hash

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#126]
Currently, in order for a cloud instance to replicate the state of a given `idc-isle-dc` commit, one would have to:
* know the commit
* Look at the `.env` file in `idc-isle-dc` to see what buildkit tag it uses
* obtain the hash of the `drupal-static` image associated with the commit.

This is error-prone.  Instead, `idc-isle-dc` should re-tag and push all images, so that the entire IDC stack can be described by a _single_ tag, equivalent to the tag `idc-isle-dc` uses for tagging `drupal-static`.

Prior to this issue, some tags of images in an IDC stack might look like:
`ghcr.io/jhu-sheridan-libraries/idc-isle-dc/fits:upstream-20200824-f8d1e8e-27-g6cd914d`
`ghcr.io/jhu-sheridan-libraries/idc-isle-dc/drupal-static:v0.0.0-18-g9e11f61`

After this issue, images of IDC stack should be tagged and pushed by idc-isle-dc as:
`ghcr.io/jhu-sheridan-libraries/idc-isle-dc/fits:v0.0.0-18-g9e11f61`
`ghcr.io/jhu-sheridan-libraries/idc-isle-dc/drupal-static:v0.0.0-18-g9e11f61`

**Comment by noahwsmith** [comment]
You may find that this snip does what you want, if I understand correctly

https://github.com/Islandora-Devops/isle-buildkit/blob/main/.github/workflows/push.yml#L28
