### ISSUE TITLE
12-media-tests tests fail on occasion in CI

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#141]
I'm noticing in PR 124 that the tests sometimes fail and sometimes work, but only in the 12-media-tests. 

There's some sort of timing issue there and I'm creating this ticket to note it and maybe keep track of it. 

The tests probably need a little more spacing in between migrating data and checking for nodes/media derivs.

**Comment by birkland** [comment]
I noticed a local failure whereby one object within a CSV of migrated objects failed to ingest.   I have not been able to find the original error message, if there ever was one.  In the image below, note the absence of "Uploaded JPEG2000 object"
![image](https://user-images.githubusercontent.com/517881/120511237-382f4780-c398-11eb-8ed6-3d9ad0844642.png)

**Comment by birkland** [comment]
@emetsger has a theory that testcafe is navigating away from the migration UI before migrations are actually done, resulting in some items _not_ being migrated.
