### ISSUE TITLE
UI Messages do not show up on pages for unauthenticated users in some scenarios

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#142]
This was found while working on the export stuff, but it's larger than that. 

Messages intended for end users do not always show up for unauthenticated users. For example, when the export finishes there is a message that tells the user they can download the file and presents a link. This message is not showing up for an unauthenticated user and it's not clear why.  The message shows up just fine for an authenticated user following the same workflow. 

It's not clear why this is the case. Could it have to do with permissions? The private file system?  Something else in Drupal?

**Comment by birkland** [comment]
If the net effect of this is merely that metadata export doesn't work for unauthenticated users, this is low-priority.  If it affects citations, then this is a fundamental blocker.

**Comment by birkland** [comment]
We do not need to implement bulk metadata download or citation download for non-authenticated users
