### ISSUE TITLE
Upgrade Content Browser

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#154]
See - [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Requires an update to pull in D9 compatability. While upgrade-status does complain about deprecations, a closed issue states that the libraries deprecation is indeed a false positive.

**Comment by dannylamb** [comment]
Resolved via https://github.com/jhu-idc/idc-isle-dc/commit/42a2794cb6d31ca55c16c408f2235465529bb5c0
