### ISSUE TITLE
Upgrade Field Group

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#156]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Module is up to date, has a deprecation on a core JS library that is removed in D9. This issue denotes that in the D9 compatibility issue a dependency on a new module was added. Not sure if iDC takes advantage of this behavior or not which may require this additional module being added and enabled.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-dc/commit/d216a2d1fa117028fa62396e5f649fa000b74f93
