### ISSUE TITLE
upgrade iDC Export Module

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#157]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Needs core_version_requirement added to make it D9 compatible. Is also a deprecation warning about how the AbstractCsv class is being used.

**Comment by birkland** [comment]
Done in https://github.com/jhu-idc/idc_export/commit/c060e02b61e422a98f54116c55600371d08885ce
