### ISSUE TITLE
upgrade IDC Migration

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#158]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Needs core_version_requirement added to make it D9 compatible.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc_migration/commit/e52a14bd908e321850f9aa0becaa17bcec253326
