### ISSUE TITLE
upgrade iDC UI Module

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#159]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Needs core_version_requirement added to make it D9 compatible.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc_ui_module/commit/317441cd7d0f19492c1bd38bd48d5b6001a07588
