### ISSUE TITLE
upgrade Islandora Defaults

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#160]
see  [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Since this is a fork the work done in the D9 sprint is not present. Given that's it's mostly config work odds are a lot of it would not be applicable. However submodule changes and others will require this to be updated.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-dc/commit/d216a2d1fa117028fa62396e5f649fa000b74f93
