### ISSUE TITLE
upgrade Islandora FITS

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#161]
see  [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Requires a version bump from the D9 sprint.

**Comment by dannylamb** [comment]
Resolved via https://github.com/jhu-idc/idc-isle-dc/commit/42a2794cb6d31ca55c16c408f2235465529bb5c0
