### ISSUE TITLE
upgrade Drupal Libraries

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#162]
see  [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Locked version has D9 support, version bump would likely be recommend here as there has been some further deprecation fixes.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-dc/commit/d216a2d1fa117028fa62396e5f649fa000b74f93
