### ISSUE TITLE
upgrade Migrate Files (extended)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#163]
see  [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Currently locked at 1.1.x requires a version bump to be able to have D9 support.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/migrate_file/commit/1c0da9e22374eb5937e6e89018e56d7fde134bc5
