### ISSUE TITLE
upgrade RDF UI

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#164]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Requires a version bump to the latest beta for D9 support.

**Comment by dannylamb** [comment]
Are y'all actually using this module?  Islandora doesn't make use of it anymore.  It's a bit of a vestige.

Removing it is harmless, but it will get updated as I move everything over to D9 regardless.   Just putting it out there that you most likely have the option to axe this.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-dc/commit/d216a2d1fa117028fa62396e5f649fa000b74f93
