### ISSUE TITLE
upgrade Reference Value Pair

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#165]
see [https://github.com/jhu-idc/idc-isle-dc/issues/71
](https://github.com/jhu-idc/idc-isle-dc/issues/71
)
No D9 version is available upstream. Their issue queue seems very inactive as there are open D9 tickets. Any D9 compatibility work would need be taken on and pushed to iDC's fork.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/reference_value_pair/commit/ee0bb998be76fc9b32884028d417fd7779df235d
