### ISSUE TITLE
Security upgrade for Drupal Core

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#167]
See https://test.digital.library.jhu.edu/admin/reports/updates

**Comment by cyork** [comment]
**Security updates available**
- 8.9.18 (2021-Aug-12)
- 9.2.4 (2021-Aug-12)

**Comment by birkland** [comment]
Resolved as of https://github.com/jhu-idc/idc-isle-dc/commit/d216a2d1fa117028fa62396e5f649fa000b74f93
