### ISSUE TITLE
update available for Tomcat

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#170]
see [https://tomcat.apache.org/whichversion.html](https://tomcat.apache.org/whichversion.html)

Latest is 10.1.x; we are on 9.0.4

**Comment by htpvu** [comment]
I think this could be done post launch, but need to be done at some point. staying up to date is one way to mitigating security risks.

**Comment by htpvu** [comment]
Bill's recommendation that we go to version 9.0.59

**Comment by little9** [comment]
@htpvu This was done 12 days ago on https://github.com/jhu-idc/idc-isle-buildkit/commit/01981d6a5c27d9b3df3220182c4310ce821eea06 , but we didn't close this ticket.
