### ISSUE TITLE
update available for ActiveMQ

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#171]
See [https://activemq.apache.org/components/classic/download/](https://activemq.apache.org/components/classic/download/)

**Comment by cyork** [comment]
ActiveMQ 5.16.3 (**Aug 17, 2021**)

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-buildkit/commit/c087eebf8c6e7ddd75a091d80f143bbfc6549fc3
