### ISSUE TITLE
update available for Cantaloupe

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#172]
See [https://github.com/cantaloupe-project/cantaloupe/releases](https://github.com/cantaloupe-project/cantaloupe/releases)

Latest is 5.0.3 on May 5; we are on 4.1.7

**Comment by little9** [comment]
Some notes about this: this is a major version update and cantaloupe is no longer distributed as a `war` file.

**Comment by birkland** [comment]
seems like a fairly major effort to update to 5.x.  Maybe just update to [4.1.9](https://github.com/cantaloupe-project/cantaloupe/releases/tag/v4.1.9) for the time being.  I'm not sure when end-of-life for the 4.x series is, would you feel up to doing some research @little9 ?

**Comment by birkland** [comment]
cc @noahwsmith  

islandora-devops/isle-buildkit upstream is even further behind at 4.1.5.  I'm not sure if 5.x is on the radar for ISLE or not.

**Comment by little9** [comment]
@birkland I'll go ahead and open a PR for 4.1.9.

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-buildkit/commit/872538d18f502df5745b67b172a5506e4a89ffdf
