### ISSUE TITLE
pull upstream changes into islandora_defaults

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#173]
See [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)
Given the forked nature of islandora_defaults any pull from upstream would need to be vetted to ensure there would be no stomping over customizations. The nature of the update is somewhat large but the main pieces would be ensuring that callbacks for fields are not utilizing deprecated functions as well the submodules have their info.ymls updated accordingly.

**Comment by birkland** [comment]
Essential stuff pulled in as of https://github.com/jhu-idc/islandora_defaults/commit/fb1aac2963687dab260440110b1192427ba4ba92

It hasn't been fully brought in line with upstream, though.  But it works for D9
