### ISSUE TITLE
pull upstream changes into refernce_value_pair

### ISSUE THREAD

**Issue by cyork** [jhu-idc/idc-isle-dc#174]
See [https://github.com/jhu-idc/idc-isle-dc/issues/71](https://github.com/jhu-idc/idc-isle-dc/issues/71)

Given the amount of work here it'd definitely be preferable to have this work undertook before launch. In terms of updating reference_value_pair and the other listed things above it's not a whole lot of development time. IMO, the updates to composer proper as well as have these changes reflected within provisioning pose the biggest risk. I'm not familiar with how ISLE handles updates (assuming there are existing boxes that would need to be updated).

**Comment by birkland** [comment]
There is no upstream to reference_value_pair, but it has been updated to D9 as of https://github.com/jhu-idc/reference_value_pair/commit/ee0bb998be76fc9b32884028d417fd7779df235d
