### ISSUE TITLE
Update to Composer 2.0

### ISSUE THREAD

**Issue by noahwsmith** [jhu-idc/idc-isle-dc#218]
@dannylamb volunteered to update the composer.json file to Composer 2.0, as @bseeger and others are now experiencing composer-related issues and this would seem to make a positive impact.

Danny notes that he may need assistance from @birkland in updating the CICD tooling to be able to run Composer 2, but he'll be in touch after he gets a little further into the task.

**Comment by birkland** [comment]
Right now, composer is installed in `nginx/Dockerfile` as a standard Alpine package, and it is a 1.x version.   CI doesn't invoke `composer` itself (nor do any `make` targets), so as long as the 2.x version as installed in the container works OK, CI should be OK.  If any special considerations are at play for the occasional developer who wishes to use their own local `composer` to do work (i.e. they too would need to upgrade to composer 2.x, or change some sort of local config file), please note that.
