### ISSUE TITLE
Figure out how to customize settings.php with environment-specific values

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#25]
The s3fs module recommends defining S3 keys in settings.php.  As per IDC conventions, we'd expect these to be set via environment variables.  Possible approaches include:
* use `confd` to templatize settings.php
* use `envsubst` to templatize settings.php
* expose environment variables to Drupal so that `settings.php` can use `getenv()`
 
See discussion in [an abandoned PR](https://github.com/jhu-idc/idc-isle-buildkit/pull/7#issuecomment-738838611)

Right now, exposing environment variables seems the most palatable approach, but it needs eyes from the team.  Write up a description and get some eyes on it.

**Comment by htpvu** [comment]
@birkland is this strictly related to Adding S3 to the bucket? is this ticket parked?
