### ISSUE TITLE
Builds fail from PRs that originate from branches in this repo

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#30]
[This PR build](https://github.com/jhu-idc/idc-isle-dc/pull/28/checks?check_run_id=1559981702#step:8:10) failed on the "docker login" step.  It should have skipped the Docker steps entirely instead.  It looks like the underlying cause is that this PR was issued from a branch in this repo.  

Currently, the workflow [tests](https://github.com/jhu-idc/idc-isle-dc/actions/runs/424215116/workflow#L46-L47) whether DOCKER_USER is null.  The assumption is that PRs won't have secrets defined.  For PRs that originate from forked repos, this assumption is true.  For PRs that originate from branches in idc-isle-dc, this assumption is false, I think.  Clearly DOCKER_USER is defined.  II have no idea why the build didn't go all the way and mistakenly push the Docker images.

Figure out a better way to determine whether to login and build the docker images.

**Comment by emetsger** [comment]
Folks, please attempt the instructions present in the Jira issue [OPS-1705](https://jhulibraries.atlassian.net/browse/OPS-1705), and record your success or failures on this issue thread.  At this juncture, the test fails for me, but succeeds for Derek.  I'd like to see how may people on the IDC dev team can successfully (or not) push to the GHCR using a GitHub action.

**Comment by birkland** [comment]
Woah, this works for me:
https://github.com/birkland/isle-dc/runs/1579025463?check_suite_focus=true

**Comment by emetsger** [comment]
> Woah, this works for me:
https://github.com/birkland/isle-dc/runs/1579025463?check_suite_focus=true

I forked your repo, dropped in values for the secrets, and it failed for me.

**Comment by htpvu** [comment]
@birkland could you add info on who currently owns this issue ?

**Comment by htpvu** [comment]
obsolete.
