### ISSUE TITLE
settings.php for DEFAULT site is not getting updated

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/idc-isle-dc#50]
When a container boots, the settings file does not get modified. This means that environment variables required to set the database are ignored and defaults are used. This is problematic because we publish the settings.php on GitHub with defaults such as `password` for the password.

From my digging, it has to do with the function `update_settings_php` in /etc/islandora/utilities.sh. Unless the site is being installed (i.e. INSTALLED=true is an environment variable), the function returns 0 before we even get to the modification portion.

I'm still working through the repercussions of setting INSTALLED=true and what that might affect for pre-existing sites as that's how our containers are going to boot, with the DEFAULT site populated with content.

**Comment by derekbelrose** [comment]
I'm not entirely sure this shouldn't be an issue in https://github.com/jhu-idc/idc-isle-buildkit

**Comment by derekbelrose** [comment]
This may relate to #25

**Comment by derekbelrose** [comment]
https://github.com/jhu-idc/idc-isle-buildkit/pull/24

This was created to work around  this process

**Comment by htpvu** [comment]
resolved by this PR https://github.com/jhu-idc/idc-isle-dc/pull/87
