### ISSUE TITLE
Remove Drupal Testing (SimpleTest) module

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#69]
We should remove this Drupal Module since it's deprecated and we don't use it (that I know of). 
According to the Drupal status page: 

> Testing (SimpleTest)
> The Testing (SimpleTest) module is deprecated for removal in Drupal 9. It should not be enabled on production sites. Read The Drupal core SimpleTest module is deprecated for alternative ways to run tests during development.

**Comment by birkland** [comment]
This is likely a prerequisite of #71

**Comment by jordandukart** [comment]
https://github.com/jhu-idc/idc-isle-dc/pull/177
