### ISSUE TITLE
EDTF date rendering inconsistencies

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/idc-isle-dc#89]
The following dates render differently and we might want to normalize how they render. 

The following date renders differently depending on which date field it's put into: 
2020-10~-10
In the Date Available field it renders like so: 
`2020-10-10 (approximate)`
In the Date Created field it renders like so: 
`2020-October-10 (approximate)`

Under content types on the [Manage Display](https://islandora-idc.traefik.me/admin/structure/types/manage/islandora_object/display) page, we can manipulate how the dates render.   Right now one date (Date Created) is set differently, by accident. 

![Screen Shot 2021-03-10 at 7 47 18 AM](https://user-images.githubusercontent.com/7966375/110632085-35e09700-8175-11eb-8faf-cbd23c88d916.png)
![Screen Shot 2021-03-10 at 7 47 32 AM](https://user-images.githubusercontent.com/7966375/110632087-35e09700-8175-11eb-85f3-18c071128df9.png)
![Screen Shot 2021-03-10 at 7 47 37 AM](https://user-images.githubusercontent.com/7966375/110632088-35e09700-8175-11eb-9d72-5fa61782d85c.png)

We should set these options consistently across dates, based on input from Katie and Michelle.

**Comment by htpvu** [comment]
@bseeger is this a config task? or is it a note for migration definition writing? or is a UI rendering requirement?

**Comment by bseeger** [comment]
It's a config task that will affect how the values handed to the UI are rendered. Very simple change.

**Comment by bseeger** [comment]
This was just a mis-configuration that needs to be corrected. Extremely minor.

**Comment by bseeger** [comment]
Addressed in: https://github.com/jhu-idc/idc-isle-dc/pull/113 
I made it so all dates render with YYYY-MM-DD, like so: 

![Screen Shot 2021-04-15 at 4 01 39 PM](https://user-images.githubusercontent.com/7966375/114932634-b98d4380-9e05-11eb-888d-4fa80d977c8a.png)

All dates are consistently rendered now.
