### ISSUE TITLE
Characterize system requirements for ingesting large files

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#91]
Using defaults stock from ISLE, large files cannot successfully be processed.  "processed" means:
* Successfully uploaded
* derivatives successfully generated and persisted.

Bethany had issues ingesting files and [took detailed notes](https://docs.google.com/document/d/1rnqxau6qCuenFaHfYyKuMS5SzxPnBUbnODN3TgmMlAc/edit)

Some data related to file size distribution for launch are present in [this spreadsheet](https://docs.google.com/spreadsheets/d/19sXx90uEDucn_zmgJJuNxGO3XTteLH1DGKBkEkcNAiM/edit#gid=0)

Characterize the resource requirements of the relevant ISLE services when ingesting the largest known file of each of the ISLE-supported media type (audio, image, video, etc)

We know that even moderately-sized files (e.g. 100 MB audio files) cause derivative failures due to timeouts, so characterizing the system will likely involve tweaking it until ingest of large files succeed.  

Specifically, characterize:
* _memory requirements_.  What are the memory requirements for uploading large images by the relevant parties (Drupal, alpaca, microservices), for each media type? 
* _timeout requirements_.  The root cause of derivative failures in #82 was http request timeouts.  Which components are using long-lived http requests, and how much of a timeout do we need?  Where are these values set/modified?
* _storage requirements_.  Does any service require temporary space while processing?  How much?  Where? 
* _settings_.  What settings are necessary to change in order to accommodate large files?  To what values? 

If you notice an inherent barrier or architectural limitation to handling large files, please make note of it.

**Comment by derekbelrose** [comment]
What are you looking for from Operations on this? Recommendations, comments, or just confirmation that we are aware of this activity?

**Comment by birkland** [comment]
@derekbelrose Looking for confirmation of sufficiency of the information that will be gathered on ticket suits the needs of ops, and at the 6/3 developers meeting, we'd be looking to calibrate the effort on this ticket, i.e. don't spend time looking for things that _aren't_ needed by ops.

**Comment by derekbelrose** [comment]
Yes that information seems sufficient to me, but I look to @jhujasonw to confirm as well. I would think we'd need values that are determined from cloud deployment tests (where it makes sense such as timeouts, settings) as opposed to local docker environments.

**Comment by jhujasonw** [comment]
I would say that the current list of needed information is indeed a good start.  I would also mention that ingest timeouts to PHP (ie. max_execution_time, max_input_time, etc) are heavily dependent on connection speeds to the system from whatever machine is doing the ingest.  Also, by upping these limits, you are effectively locking the web server task that is doing that ingest for that amount of time.  If there is a connection issue, the process on the server side will block that amount of time before assuming an issue.  It's also not clear of those timeouts are parallel or additive.

**Comment by birkland** [comment]
Report, new env vars and tweaks documented here:
https://docs.google.com/document/d/1IunoC6tmJkABdF-KRKyux3WdK5dJiG67y-yuDYxFyOI/edit?usp=sharing

**Comment by emetsger** [comment]
Closed per above link to document.
