### ISSUE TITLE
Characterize parallelization of derivative generation

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-dc#93]
If we want to rightly-size the resources for running a microservice, we need to be able to reason about the number of tasks (e.g. image resizing) each microservice performs at the same time, in parallel. 

We know that:
* Alpaca runs camel routes that invoke microservices to perform a derivative, in response to messages that new content is available that needs derivative generation.
* Each microservice has its own camel route running in Alpaca that invokes it, and all camel routes operate independently.

Please find our unknowns:
* How many concurrent requests to a given microservice an Alpaca camel route will make, out of the box?
* Can the number of concurrent requests to a microservice can be changed via configuration?

**Comment by emetsger** [comment]
Document characterizing derivative generation, including parallelization of derivative production is here: https://docs.google.com/document/d/1IunoC6tmJkABdF-KRKyux3WdK5dJiG67y-yuDYxFyOI/edit#
